# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: train-pod-team-a
  labels:
    runai/queue: team-a
    priorityClassName: train
spec:
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  schedulerName: kai-scheduler
  containers:
    - name: sleep
      image: busybox
      args: ["sh","-c","sleep infinity"]
      resources:
        limits:
          nvidia.com/gpu: "3"
