/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/client/clientset/versioned/typed/scheduling/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSchedulingV1alpha2 struct {
	*testing.Fake
}

func (c *FakeSchedulingV1alpha2) BindRequests(namespace string) v1alpha2.BindRequestInterface {
	return newFakeBindRequests(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSchedulingV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
