# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: gpu-sharing
  labels:
    runai/queue: test
  annotations:
    gpu-fraction: "0.5"
spec:
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  schedulerName: kai-scheduler
  containers:
    - name: sleep
      image: busybox
      args: ["sh","-c","sleep infinity"]
