/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v2alpha2

// PodGroupListerExpansion allows custom methods to be added to
// PodGroupLister.
type PodGroupListerExpansion interface{}

// PodGroupNamespaceListerExpansion allows custom methods to be added to
// PodGroupNamespaceLister.
type PodGroupNamespaceListerExpansion interface{}
