# Copyright 2025 NVIDIA CORPORATION
  # SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-reservation
  namespace: runai-reservation
subjects:
  - kind: ServiceAccount
    name: runai-reservation
    namespace: runai-reservation
roleRef:
  kind: ClusterRole
  name: resource-reservation
  apiGroup: rbac.authorization.k8s.io
