/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	scheme "github.com/NVIDIA/KAI-scheduler/pkg/apis/client/clientset/versioned/scheme"
	schedulingv2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/scheduling/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// QueuesGetter has a method to return a QueueInterface.
// A group's client should implement this interface.
type QueuesGetter interface {
	Queues(namespace string) QueueInterface
}

// QueueInterface has methods to work with Queue resources.
type QueueInterface interface {
	Create(ctx context.Context, queue *schedulingv2.Queue, opts v1.CreateOptions) (*schedulingv2.Queue, error)
	Update(ctx context.Context, queue *schedulingv2.Queue, opts v1.UpdateOptions) (*schedulingv2.Queue, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, queue *schedulingv2.Queue, opts v1.UpdateOptions) (*schedulingv2.Queue, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schedulingv2.Queue, error)
	List(ctx context.Context, opts v1.ListOptions) (*schedulingv2.QueueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schedulingv2.Queue, err error)
	QueueExpansion
}

// queues implements QueueInterface
type queues struct {
	*gentype.ClientWithList[*schedulingv2.Queue, *schedulingv2.QueueList]
}

// newQueues returns a Queues
func newQueues(c *SchedulingV2Client, namespace string) *queues {
	return &queues{
		gentype.NewClientWithList[*schedulingv2.Queue, *schedulingv2.QueueList](
			"queues",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *schedulingv2.Queue { return &schedulingv2.Queue{} },
			func() *schedulingv2.QueueList { return &schedulingv2.QueueList{} },
		),
	}
}
