/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/client/clientset/versioned/typed/scheduling/v2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSchedulingV2 struct {
	*testing.Fake
}

func (c *FakeSchedulingV2) Queues(namespace string) v2.QueueInterface {
	return newFakeQueues(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSchedulingV2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
