/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	schedulingv2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/client/clientset/versioned/typed/scheduling/v2"
	v2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/scheduling/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeQueues implements QueueInterface
type fakeQueues struct {
	*gentype.FakeClientWithList[*v2.Queue, *v2.QueueList]
	Fake *FakeSchedulingV2
}

func newFakeQueues(fake *FakeSchedulingV2, namespace string) schedulingv2.QueueInterface {
	return &fakeQueues{
		gentype.NewFakeClientWithList[*v2.Queue, *v2.QueueList](
			fake.Fake,
			namespace,
			v2.SchemeGroupVersion.WithResource("queues"),
			v2.SchemeGroupVersion.WithKind("Queue"),
			func() *v2.Queue { return &v2.Queue{} },
			func() *v2.QueueList { return &v2.QueueList{} },
			func(dst, src *v2.QueueList) { dst.ListMeta = src.ListMeta },
			func(list *v2.QueueList) []*v2.Queue { return gentype.ToPointerSlice(list.Items) },
			func(list *v2.QueueList, items []*v2.Queue) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
