//go:build !ignore_autogenerated

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/resource/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequest) DeepCopyInto(out *BindRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequest.
func (in *BindRequest) DeepCopy() *BindRequest {
	if in == nil {
		return nil
	}
	out := new(BindRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequestList) DeepCopyInto(out *BindRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BindRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequestList.
func (in *BindRequestList) DeepCopy() *BindRequestList {
	if in == nil {
		return nil
	}
	out := new(BindRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequestSpec) DeepCopyInto(out *BindRequestSpec) {
	*out = *in
	if in.ReceivedGPU != nil {
		in, out := &in.ReceivedGPU, &out.ReceivedGPU
		*out = new(ReceivedGPU)
		**out = **in
	}
	if in.SelectedGPUGroups != nil {
		in, out := &in.SelectedGPUGroups, &out.SelectedGPUGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceClaimAllocations != nil {
		in, out := &in.ResourceClaimAllocations, &out.ResourceClaimAllocations
		*out = make([]ResourceClaimAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequestSpec.
func (in *BindRequestSpec) DeepCopy() *BindRequestSpec {
	if in == nil {
		return nil
	}
	out := new(BindRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindRequestStatus) DeepCopyInto(out *BindRequestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindRequestStatus.
func (in *BindRequestStatus) DeepCopy() *BindRequestStatus {
	if in == nil {
		return nil
	}
	out := new(BindRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceivedGPU) DeepCopyInto(out *ReceivedGPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceivedGPU.
func (in *ReceivedGPU) DeepCopy() *ReceivedGPU {
	if in == nil {
		return nil
	}
	out := new(ReceivedGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimAllocation) DeepCopyInto(out *ResourceClaimAllocation) {
	*out = *in
	if in.Allocation != nil {
		in, out := &in.Allocation, &out.Allocation
		*out = new(v1beta1.AllocationResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimAllocation.
func (in *ResourceClaimAllocation) DeepCopy() *ResourceClaimAllocation {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimAllocation)
	in.DeepCopyInto(out)
	return out
}
