/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	schedulingv1alpha2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/scheduling/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BindRequestLister helps list BindRequests.
// All objects returned here must be treated as read-only.
type BindRequestLister interface {
	// List lists all BindRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha2.BindRequest, err error)
	// BindRequests returns an object that can list and get BindRequests.
	BindRequests(namespace string) BindRequestNamespaceLister
	BindRequestListerExpansion
}

// bindRequestLister implements the BindRequestLister interface.
type bindRequestLister struct {
	listers.ResourceIndexer[*schedulingv1alpha2.BindRequest]
}

// NewBindRequestLister returns a new BindRequestLister.
func NewBindRequestLister(indexer cache.Indexer) BindRequestLister {
	return &bindRequestLister{listers.New[*schedulingv1alpha2.BindRequest](indexer, schedulingv1alpha2.Resource("bindrequest"))}
}

// BindRequests returns an object that can list and get BindRequests.
func (s *bindRequestLister) BindRequests(namespace string) BindRequestNamespaceLister {
	return bindRequestNamespaceLister{listers.NewNamespaced[*schedulingv1alpha2.BindRequest](s.ResourceIndexer, namespace)}
}

// BindRequestNamespaceLister helps list and get BindRequests.
// All objects returned here must be treated as read-only.
type BindRequestNamespaceLister interface {
	// List lists all BindRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha2.BindRequest, err error)
	// Get retrieves the BindRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*schedulingv1alpha2.BindRequest, error)
	BindRequestNamespaceListerExpansion
}

// bindRequestNamespaceLister implements the BindRequestNamespaceLister
// interface.
type bindRequestNamespaceLister struct {
	listers.ResourceIndexer[*schedulingv1alpha2.BindRequest]
}
