/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// BindRequestListerExpansion allows custom methods to be added to
// BindRequestLister.
type BindRequestListerExpansion interface{}

// BindRequestNamespaceListerExpansion allows custom methods to be added to
// BindRequestNamespaceLister.
type BindRequestNamespaceListerExpansion interface{}
