/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/client/clientset/versioned/typed/scheduling/v2alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSchedulingV2alpha2 struct {
	*testing.Fake
}

func (c *FakeSchedulingV2alpha2) PodGroups(namespace string) v2alpha2.PodGroupInterface {
	return newFakePodGroups(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSchedulingV2alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
