/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v2

// QueueListerExpansion allows custom methods to be added to
// QueueLister.
type QueueListerExpansion interface{}

// QueueNamespaceListerExpansion allows custom methods to be added to
// QueueNamespaceLister.
type QueueNamespaceListerExpansion interface{}
