/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package v2alpha2

import (
	context "context"

	scheme "github.com/NVIDIA/KAI-scheduler/pkg/apis/client/clientset/versioned/scheme"
	schedulingv2alpha2 "github.com/NVIDIA/KAI-scheduler/pkg/apis/scheduling/v2alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodGroupsGetter has a method to return a PodGroupInterface.
// A group's client should implement this interface.
type PodGroupsGetter interface {
	PodGroups(namespace string) PodGroupInterface
}

// PodGroupInterface has methods to work with PodGroup resources.
type PodGroupInterface interface {
	Create(ctx context.Context, podGroup *schedulingv2alpha2.PodGroup, opts v1.CreateOptions) (*schedulingv2alpha2.PodGroup, error)
	Update(ctx context.Context, podGroup *schedulingv2alpha2.PodGroup, opts v1.UpdateOptions) (*schedulingv2alpha2.PodGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podGroup *schedulingv2alpha2.PodGroup, opts v1.UpdateOptions) (*schedulingv2alpha2.PodGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schedulingv2alpha2.PodGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*schedulingv2alpha2.PodGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schedulingv2alpha2.PodGroup, err error)
	PodGroupExpansion
}

// podGroups implements PodGroupInterface
type podGroups struct {
	*gentype.ClientWithList[*schedulingv2alpha2.PodGroup, *schedulingv2alpha2.PodGroupList]
}

// newPodGroups returns a PodGroups
func newPodGroups(c *SchedulingV2alpha2Client, namespace string) *podGroups {
	return &podGroups{
		gentype.NewClientWithList[*schedulingv2alpha2.PodGroup, *schedulingv2alpha2.PodGroupList](
			"podgroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *schedulingv2alpha2.PodGroup { return &schedulingv2alpha2.PodGroup{} },
			func() *schedulingv2alpha2.PodGroupList { return &schedulingv2alpha2.PodGroupList{} },
		),
	}
}
