//go:build !ignore_autogenerated

/*
Copyright 2025 NVIDIA CORPORATION
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha2

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroup) DeepCopyInto(out *PodGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroup.
func (in *PodGroup) DeepCopy() *PodGroup {
	if in == nil {
		return nil
	}
	out := new(PodGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupCondition) DeepCopyInto(out *PodGroupCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupCondition.
func (in *PodGroupCondition) DeepCopy() *PodGroupCondition {
	if in == nil {
		return nil
	}
	out := new(PodGroupCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupList) DeepCopyInto(out *PodGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupList.
func (in *PodGroupList) DeepCopy() *PodGroupList {
	if in == nil {
		return nil
	}
	out := new(PodGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupResourcesStatus) DeepCopyInto(out *PodGroupResourcesStatus) {
	*out = *in
	if in.Allocated != nil {
		in, out := &in.Allocated, &out.Allocated
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AllocatedNonPreemptible != nil {
		in, out := &in.AllocatedNonPreemptible, &out.AllocatedNonPreemptible
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requested != nil {
		in, out := &in.Requested, &out.Requested
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupResourcesStatus.
func (in *PodGroupResourcesStatus) DeepCopy() *PodGroupResourcesStatus {
	if in == nil {
		return nil
	}
	out := new(PodGroupResourcesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupSpec) DeepCopyInto(out *PodGroupSpec) {
	*out = *in
	if in.MarkUnschedulable != nil {
		in, out := &in.MarkUnschedulable, &out.MarkUnschedulable
		*out = new(bool)
		**out = **in
	}
	if in.SchedulingBackoff != nil {
		in, out := &in.SchedulingBackoff, &out.SchedulingBackoff
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupSpec.
func (in *PodGroupSpec) DeepCopy() *PodGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PodGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupStatus) DeepCopyInto(out *PodGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PodGroupCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourcesStatus.DeepCopyInto(&out.ResourcesStatus)
	if in.SchedulingConditions != nil {
		in, out := &in.SchedulingConditions, &out.SchedulingConditions
		*out = make([]SchedulingCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupStatus.
func (in *PodGroupStatus) DeepCopy() *PodGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PodGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaDetails) DeepCopyInto(out *QuotaDetails) {
	*out = *in
	if in.QueueRequestedResources != nil {
		in, out := &in.QueueRequestedResources, &out.QueueRequestedResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.QueueDeservedResources != nil {
		in, out := &in.QueueDeservedResources, &out.QueueDeservedResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.QueueAllocatedResources != nil {
		in, out := &in.QueueAllocatedResources, &out.QueueAllocatedResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.QueueAllocatedNonPreemptibleResources != nil {
		in, out := &in.QueueAllocatedNonPreemptibleResources, &out.QueueAllocatedNonPreemptibleResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.QueueResourceLimits != nil {
		in, out := &in.QueueResourceLimits, &out.QueueResourceLimits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.PodGroupRequestedResources != nil {
		in, out := &in.PodGroupRequestedResources, &out.PodGroupRequestedResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.PodGroupRequestedNonPreemptibleResources != nil {
		in, out := &in.PodGroupRequestedNonPreemptibleResources, &out.PodGroupRequestedNonPreemptibleResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaDetails.
func (in *QuotaDetails) DeepCopy() *QuotaDetails {
	if in == nil {
		return nil
	}
	out := new(QuotaDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingCondition) DeepCopyInto(out *SchedulingCondition) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make(UnschedulableExplanations, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingCondition.
func (in *SchedulingCondition) DeepCopy() *SchedulingCondition {
	if in == nil {
		return nil
	}
	out := new(SchedulingCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnschedulableExplanation) DeepCopyInto(out *UnschedulableExplanation) {
	*out = *in
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(UnschedulableExplanationDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnschedulableExplanation.
func (in *UnschedulableExplanation) DeepCopy() *UnschedulableExplanation {
	if in == nil {
		return nil
	}
	out := new(UnschedulableExplanation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnschedulableExplanationDetails) DeepCopyInto(out *UnschedulableExplanationDetails) {
	*out = *in
	if in.QueueDetails != nil {
		in, out := &in.QueueDetails, &out.QueueDetails
		*out = new(QuotaDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnschedulableExplanationDetails.
func (in *UnschedulableExplanationDetails) DeepCopy() *UnschedulableExplanationDetails {
	if in == nil {
		return nil
	}
	out := new(UnschedulableExplanationDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in UnschedulableExplanations) DeepCopyInto(out *UnschedulableExplanations) {
	{
		in := &in
		*out = make(UnschedulableExplanations, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnschedulableExplanations.
func (in UnschedulableExplanations) DeepCopy() UnschedulableExplanations {
	if in == nil {
		return nil
	}
	out := new(UnschedulableExplanations)
	in.DeepCopyInto(out)
	return *out
}
