# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podgrouper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podgrouper
  template:
    metadata:
      labels:
        app: podgrouper
    spec:
      serviceAccountName: podgrouper
      containers:
        - name: podgrouper
          image: "{{ .Values.global.registry }}/{{ .Values.podgrouper.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.podgrouper.image.pullPolicy }}
          {{- if .Values.podgrouper.args }}
          args:
            {{- toYaml .Values.podgrouper.args | nindent 12 }}
          {{- end }}
          {{- if .Values.podgrouper.resources }}
          resources:
            {{- toYaml .Values.podgrouper.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}